version: '3.8'

services:
  postgres:
    container_name: api-puro
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mentores
      - POSTGRES_PASSWORD=mentores
      - POSTGRES_DB=puro-db
      - PGDATA=/data/postgres

    volumes:
      - ./data/pg:/data/postgres
